name: Run Linting in the project
on: [pull_request]

jobs:
  lint:
    name: Linting auto fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Install dependency
        run: npm i nx@18.1.1

      - name: Run lint fix
        run: npm run lint:fix

      - name: Run lint
        run: npm run lint | tee lint_result.txt

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run reviewdog
        run: |
          reviewdog -efm="%f:%l:%c: %m" -name="eslint" -reporter=github-pr-review -filter-mode=file < lint_result.txt
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
